# Configure Netlify builds.
[build]
  publish = "dist/"
  command = "npm run build"

# Request bots not to index the admin section.
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# Redirect /admin to /admin/ for SPA routing
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200

# Handle SPA routing for blog admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/"
  status = 200
