backend:
  name: github
  repo: ramonpando/bravix-blog
  branch: main

media_folder: public/assets/blog
public_folder: /blog/assets/blog

collections:
  - name: posts
    label: Blog Posts
    folder: src/pages/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: publishDate
        widget: datetime
      - label: Description
        name: description
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown